apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: homework-volume
      emptyDir: {}

  initContainers:
    - name: init-index
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - echo '<h1>Hello from homework</h1>' > /init/index.html
      volumeMounts:
        - name: homework-volume
          mountPath: /init

  containers:
    - name: web
      image: python:3.9-slim
      command: ["python3", "-m", "http.server", "8000", "--directory", "/homework"]
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: homework-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
